
[other]
	proc_title = false

	[other.sceptrepearl]
		sceptrepearl = false

	[other.refills]
		superboomrefill = false
		pearlrefill = true
		boomrefill = true

	[other.pjoin]
		pjoin = true

	[other.miningability]
		miningability = true
		sound = true

	[other.pearlrefill]
		pearlrefill = true

	[other.invincibility_procs]
		only_in_dungeons = true
		only_in_p3 = true
		show_when_ready = true
		invprocs_display = true
		proc_title = true
		ready_title = true
		announce = true

	[other.helmet_display]
		helmet_display = true

[dev]
	firstload = false

[dungeons]

	[dungeons.deathtitle]
		rev_title = true
		deathtitle = true

	[dungeons.m5rq]
		delay = 1000
		m5rq = false

	[dungeons.betterbeam]
		betterbeam = true

	[dungeons.ghostpick]
		continuous = true
		ghostpick = false
		slot = 4
		dungeons_only = true

